/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   main__grage_door_message__init
                     (Main__GrageDoorMessage         *message)
{
  static const Main__GrageDoorMessage init_value = MAIN__GRAGE_DOOR_MESSAGE__INIT;
  *message = init_value;
}
size_t main__grage_door_message__get_packed_size
                     (const Main__GrageDoorMessage *message)
{
  assert(message->base.descriptor == &main__grage_door_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__grage_door_message__pack
                     (const Main__GrageDoorMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__grage_door_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__grage_door_message__pack_to_buffer
                     (const Main__GrageDoorMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__grage_door_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__GrageDoorMessage *
       main__grage_door_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__GrageDoorMessage *)
     protobuf_c_message_unpack (&main__grage_door_message__descriptor,
                                allocator, len, data);
}
void   main__grage_door_message__free_unpacked
                     (Main__GrageDoorMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__grage_door_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   main__oleddisplay__init
                     (Main__OLEDDisplay         *message)
{
  static const Main__OLEDDisplay init_value = MAIN__OLEDDISPLAY__INIT;
  *message = init_value;
}
size_t main__oleddisplay__get_packed_size
                     (const Main__OLEDDisplay *message)
{
  assert(message->base.descriptor == &main__oleddisplay__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t main__oleddisplay__pack
                     (const Main__OLEDDisplay *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &main__oleddisplay__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t main__oleddisplay__pack_to_buffer
                     (const Main__OLEDDisplay *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &main__oleddisplay__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Main__OLEDDisplay *
       main__oleddisplay__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Main__OLEDDisplay *)
     protobuf_c_message_unpack (&main__oleddisplay__descriptor,
                                allocator, len, data);
}
void   main__oleddisplay__free_unpacked
                     (Main__OLEDDisplay *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &main__oleddisplay__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue main__grage_door_message__message_type__enum_values_by_number[7] =
{
  { "OPEN", "MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__OPEN", 0 },
  { "RECVD", "MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__RECVD", 1 },
  { "ACCEPTED_OPENING", "MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__ACCEPTED_OPENING", 10 },
  { "ACCEPTED_CLOSING", "MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__ACCEPTED_CLOSING", 11 },
  { "DENIED_UNAUTH", "MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__DENIED_UNAUTH", 20 },
  { "DENIED_OOB_TIME", "MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__DENIED_OOB_TIME", 21 },
  { "DENIED_OOB_GEOFENCE", "MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__DENIED_OOB_GEOFENCE", 29 },
};
static const ProtobufCIntRange main__grage_door_message__message_type__value_ranges[] = {
{0, 0},{10, 2},{20, 4},{29, 6},{0, 7}
};
static const ProtobufCEnumValueIndex main__grage_door_message__message_type__enum_values_by_name[7] =
{
  { "ACCEPTED_CLOSING", 3 },
  { "ACCEPTED_OPENING", 2 },
  { "DENIED_OOB_GEOFENCE", 6 },
  { "DENIED_OOB_TIME", 5 },
  { "DENIED_UNAUTH", 4 },
  { "OPEN", 0 },
  { "RECVD", 1 },
};
const ProtobufCEnumDescriptor main__grage_door_message__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "main.GrageDoorMessage.MessageType",
  "MessageType",
  "Main__GrageDoorMessage__MessageType",
  "main",
  7,
  main__grage_door_message__message_type__enum_values_by_number,
  7,
  main__grage_door_message__message_type__enum_values_by_name,
  4,
  main__grage_door_message__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor main__grage_door_message__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__GrageDoorMessage, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ts",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Main__GrageDoorMessage, ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__GrageDoorMessage, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__GrageDoorMessage, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channel",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Main__GrageDoorMessage, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nmea",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Main__GrageDoorMessage, nmea),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Main__GrageDoorMessage, type),
    &main__grage_door_message__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__grage_door_message__field_indices_by_name[] = {
  4,   /* field[4] = channel */
  0,   /* field[0] = id */
  3,   /* field[3] = mac */
  5,   /* field[5] = nmea */
  2,   /* field[2] = nonce */
  1,   /* field[1] = ts */
  6,   /* field[6] = type */
};
static const ProtobufCIntRange main__grage_door_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 6 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor main__grage_door_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.GrageDoorMessage",
  "GrageDoorMessage",
  "Main__GrageDoorMessage",
  "main",
  sizeof(Main__GrageDoorMessage),
  7,
  main__grage_door_message__field_descriptors,
  main__grage_door_message__field_indices_by_name,
  2,  main__grage_door_message__number_ranges,
  (ProtobufCMessageInit) main__grage_door_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor main__oleddisplay__field_descriptors[4] =
{
  {
    "clear",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Main__OLEDDisplay, clear),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line1",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__OLEDDisplay, line1),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line2",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__OLEDDisplay, line2),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line3",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Main__OLEDDisplay, line3),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned main__oleddisplay__field_indices_by_name[] = {
  0,   /* field[0] = clear */
  1,   /* field[1] = line1 */
  2,   /* field[2] = line2 */
  3,   /* field[3] = line3 */
};
static const ProtobufCIntRange main__oleddisplay__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor main__oleddisplay__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "main.OLEDDisplay",
  "OLEDDisplay",
  "Main__OLEDDisplay",
  "main",
  sizeof(Main__OLEDDisplay),
  4,
  main__oleddisplay__field_descriptors,
  main__oleddisplay__field_indices_by_name,
  1,  main__oleddisplay__number_ranges,
  (ProtobufCMessageInit) main__oleddisplay__init,
  NULL,NULL,NULL    /* reserved[123] */
};
