# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0emessages.proto\x12\x04main\"\xa9\x02\n\x10GrageDoorMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\x04\x12\r\n\x05nonce\x18\x03 \x01(\x0c\x12\x0b\n\x03mac\x18\x04 \x01(\x0c\x12\x0f\n\x07\x63hannel\x18\x05 \x01(\r\x12\x0c\n\x04nmea\x18\x06 \x01(\x0c\x12\x30\n\x04type\x18\n \x01(\x0e\x32\".main.GrageDoorMessage.MessageType\"\x8f\x01\n\x0bMessageType\x12\x08\n\x04OPEN\x10\x00\x12\t\n\x05RECVD\x10\x01\x12\x14\n\x10\x41\x43\x43\x45PTED_OPENING\x10\n\x12\x14\n\x10\x41\x43\x43\x45PTED_CLOSING\x10\x0b\x12\x11\n\rDENIED_UNAUTH\x10\x14\x12\x13\n\x0f\x44\x45NIED_OOB_TIME\x10\x15\x12\x17\n\x13\x44\x45NIED_OOB_GEOFENCE\x10\x1d\x62\x06proto3'
)



_GRAGEDOORMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='main.GrageDoorMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECVD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED_OPENING', index=2, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED_CLOSING', index=3, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENIED_UNAUTH', index=4, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENIED_OOB_TIME', index=5, number=21,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENIED_OOB_GEOFENCE', index=6, number=29,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=179,
  serialized_end=322,
)
_sym_db.RegisterEnumDescriptor(_GRAGEDOORMESSAGE_MESSAGETYPE)


_GRAGEDOORMESSAGE = _descriptor.Descriptor(
  name='GrageDoorMessage',
  full_name='main.GrageDoorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='main.GrageDoorMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='main.GrageDoorMessage.ts', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='main.GrageDoorMessage.nonce', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='main.GrageDoorMessage.mac', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='main.GrageDoorMessage.channel', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nmea', full_name='main.GrageDoorMessage.nmea', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='main.GrageDoorMessage.type', index=6,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GRAGEDOORMESSAGE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=322,
)

_GRAGEDOORMESSAGE.fields_by_name['type'].enum_type = _GRAGEDOORMESSAGE_MESSAGETYPE
_GRAGEDOORMESSAGE_MESSAGETYPE.containing_type = _GRAGEDOORMESSAGE
DESCRIPTOR.message_types_by_name['GrageDoorMessage'] = _GRAGEDOORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrageDoorMessage = _reflection.GeneratedProtocolMessageType('GrageDoorMessage', (_message.Message,), {
  'DESCRIPTOR' : _GRAGEDOORMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:main.GrageDoorMessage)
  })
_sym_db.RegisterMessage(GrageDoorMessage)


# @@protoc_insertion_point(module_scope)
