/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

#ifndef PROTOBUF_C_messages_2eproto__INCLUDED
#define PROTOBUF_C_messages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Main__GrageDoorMessage Main__GrageDoorMessage;
typedef struct _Main__OLEDDisplay Main__OLEDDisplay;


/* --- enums --- */

typedef enum _Main__GrageDoorMessage__MessageType {
  MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__OPEN = 0,
  MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__RECVD = 1,
  MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__ACCEPTED_OPENING = 10,
  MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__ACCEPTED_CLOSING = 11,
  MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__DENIED_UNAUTH = 20,
  MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__DENIED_OOB_TIME = 21,
  MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__DENIED_OOB_GEOFENCE = 29
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE)
} Main__GrageDoorMessage__MessageType;

/* --- messages --- */

struct  _Main__GrageDoorMessage
{
  ProtobufCMessage base;
  char *id;
  uint64_t ts;
  ProtobufCBinaryData nonce;
  ProtobufCBinaryData mac;
  uint32_t channel;
  ProtobufCBinaryData nmea;
  Main__GrageDoorMessage__MessageType type;
};
#define MAIN__GRAGE_DOOR_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&main__grage_door_message__descriptor) \
    , (char *)protobuf_c_empty_string, 0, {0,NULL}, {0,NULL}, 0, {0,NULL}, MAIN__GRAGE_DOOR_MESSAGE__MESSAGE_TYPE__OPEN }


struct  _Main__OLEDDisplay
{
  ProtobufCMessage base;
  protobuf_c_boolean clear;
  char *line1;
  char *line2;
  char *line3;
};
#define MAIN__OLEDDISPLAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&main__oleddisplay__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Main__GrageDoorMessage methods */
void   main__grage_door_message__init
                     (Main__GrageDoorMessage         *message);
size_t main__grage_door_message__get_packed_size
                     (const Main__GrageDoorMessage   *message);
size_t main__grage_door_message__pack
                     (const Main__GrageDoorMessage   *message,
                      uint8_t             *out);
size_t main__grage_door_message__pack_to_buffer
                     (const Main__GrageDoorMessage   *message,
                      ProtobufCBuffer     *buffer);
Main__GrageDoorMessage *
       main__grage_door_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   main__grage_door_message__free_unpacked
                     (Main__GrageDoorMessage *message,
                      ProtobufCAllocator *allocator);
/* Main__OLEDDisplay methods */
void   main__oleddisplay__init
                     (Main__OLEDDisplay         *message);
size_t main__oleddisplay__get_packed_size
                     (const Main__OLEDDisplay   *message);
size_t main__oleddisplay__pack
                     (const Main__OLEDDisplay   *message,
                      uint8_t             *out);
size_t main__oleddisplay__pack_to_buffer
                     (const Main__OLEDDisplay   *message,
                      ProtobufCBuffer     *buffer);
Main__OLEDDisplay *
       main__oleddisplay__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   main__oleddisplay__free_unpacked
                     (Main__OLEDDisplay *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Main__GrageDoorMessage_Closure)
                 (const Main__GrageDoorMessage *message,
                  void *closure_data);
typedef void (*Main__OLEDDisplay_Closure)
                 (const Main__OLEDDisplay *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor main__grage_door_message__descriptor;
extern const ProtobufCEnumDescriptor    main__grage_door_message__message_type__descriptor;
extern const ProtobufCMessageDescriptor main__oleddisplay__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_2eproto__INCLUDED */
