# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_v2.proto',
  package='messages2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11messages_v2.proto\x12\tmessages2\"1\n\rHotpHmacCreds\x12\r\n\x05nonce\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"\xcf\x02\n\x11GarageDoorMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x36\n\x04type\x18\x02 \x01(\x0e\x32(.messages2.GarageDoorMessage.MessageType\x12\'\n\x05\x63reds\x18\x03 \x01(\x0b\x32\x18.messages2.HotpHmacCreds\x12\x0c\n\x04nmea\x18\x06 \x01(\x0c\"\xbe\x01\n\x0bMessageType\x12\x08\n\x04OPEN\x10\x00\x12\t\n\x05RECVD\x10\x01\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\n\x12\x14\n\x10\x41\x43\x43\x45PTED_OPENING\x10\x0b\x12\x14\n\x10\x41\x43\x43\x45PTED_CLOSING\x10\x0c\x12\n\n\x06\x44\x45NIED\x10(\x12\x11\n\rDENIED_UNAUTH\x10)\x12\x12\n\x0e\x44\x45NIED_REVOKED\x10*\x12\x14\n\x10\x44\x45NIED_OOB_COUNT\x10+\x12\x17\n\x13\x44\x45NIED_OOB_GEOFENCE\x10,b\x06proto3'
)



_GARAGEDOORMESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='messages2.GarageDoorMessage.MessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RECVD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED', index=2, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED_OPENING', index=3, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACCEPTED_CLOSING', index=4, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DENIED', index=5, number=40,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DENIED_UNAUTH', index=6, number=41,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DENIED_REVOKED', index=7, number=42,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DENIED_OOB_COUNT', index=8, number=43,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DENIED_OOB_GEOFENCE', index=9, number=44,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=229,
  serialized_end=419,
)
_sym_db.RegisterEnumDescriptor(_GARAGEDOORMESSAGE_MESSAGETYPE)


_HOTPHMACCREDS = _descriptor.Descriptor(
  name='HotpHmacCreds',
  full_name='messages2.HotpHmacCreds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nonce', full_name='messages2.HotpHmacCreds.nonce', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='messages2.HotpHmacCreds.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=81,
)


_GARAGEDOORMESSAGE = _descriptor.Descriptor(
  name='GarageDoorMessage',
  full_name='messages2.GarageDoorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='messages2.GarageDoorMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='messages2.GarageDoorMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creds', full_name='messages2.GarageDoorMessage.creds', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nmea', full_name='messages2.GarageDoorMessage.nmea', index=3,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GARAGEDOORMESSAGE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=419,
)

_GARAGEDOORMESSAGE.fields_by_name['type'].enum_type = _GARAGEDOORMESSAGE_MESSAGETYPE
_GARAGEDOORMESSAGE.fields_by_name['creds'].message_type = _HOTPHMACCREDS
_GARAGEDOORMESSAGE_MESSAGETYPE.containing_type = _GARAGEDOORMESSAGE
DESCRIPTOR.message_types_by_name['HotpHmacCreds'] = _HOTPHMACCREDS
DESCRIPTOR.message_types_by_name['GarageDoorMessage'] = _GARAGEDOORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HotpHmacCreds = _reflection.GeneratedProtocolMessageType('HotpHmacCreds', (_message.Message,), {
  'DESCRIPTOR' : _HOTPHMACCREDS,
  '__module__' : 'messages_v2_pb2'
  # @@protoc_insertion_point(class_scope:messages2.HotpHmacCreds)
  })
_sym_db.RegisterMessage(HotpHmacCreds)

GarageDoorMessage = _reflection.GeneratedProtocolMessageType('GarageDoorMessage', (_message.Message,), {
  'DESCRIPTOR' : _GARAGEDOORMESSAGE,
  '__module__' : 'messages_v2_pb2'
  # @@protoc_insertion_point(class_scope:messages2.GarageDoorMessage)
  })
_sym_db.RegisterMessage(GarageDoorMessage)


# @@protoc_insertion_point(module_scope)
