// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_v2.proto

#include "messages_v2.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_messages_5fv2_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_HotpHmacCreds_messages_5fv2_2eproto;
namespace messages2 {
class HotpHmacCredsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<HotpHmacCreds> _instance;
} _HotpHmacCreds_default_instance_;
class GarageDoorMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GarageDoorMessage> _instance;
} _GarageDoorMessage_default_instance_;
}  // namespace messages2
static void InitDefaultsscc_info_GarageDoorMessage_messages_5fv2_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::messages2::_GarageDoorMessage_default_instance_;
    new (ptr) ::messages2::GarageDoorMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GarageDoorMessage_messages_5fv2_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_GarageDoorMessage_messages_5fv2_2eproto}, {
      &scc_info_HotpHmacCreds_messages_5fv2_2eproto.base,}};

static void InitDefaultsscc_info_HotpHmacCreds_messages_5fv2_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::messages2::_HotpHmacCreds_default_instance_;
    new (ptr) ::messages2::HotpHmacCreds();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_HotpHmacCreds_messages_5fv2_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_HotpHmacCreds_messages_5fv2_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_messages_5fv2_2eproto[2];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_messages_5fv2_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_messages_5fv2_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_messages_5fv2_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messages2::HotpHmacCreds, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::messages2::HotpHmacCreds, nonce_),
  PROTOBUF_FIELD_OFFSET(::messages2::HotpHmacCreds, signature_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::messages2::GarageDoorMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::messages2::GarageDoorMessage, id_),
  PROTOBUF_FIELD_OFFSET(::messages2::GarageDoorMessage, type_),
  PROTOBUF_FIELD_OFFSET(::messages2::GarageDoorMessage, creds_),
  PROTOBUF_FIELD_OFFSET(::messages2::GarageDoorMessage, nmea_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::messages2::HotpHmacCreds)},
  { 7, -1, sizeof(::messages2::GarageDoorMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::messages2::_HotpHmacCreds_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::messages2::_GarageDoorMessage_default_instance_),
};

const char descriptor_table_protodef_messages_5fv2_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021messages_v2.proto\022\tmessages2\"1\n\rHotpHm"
  "acCreds\022\r\n\005nonce\030\001 \001(\014\022\021\n\tsignature\030\002 \001("
  "\014\"\317\002\n\021GarageDoorMessage\022\n\n\002id\030\001 \001(\t\0226\n\004t"
  "ype\030\002 \001(\0162(.messages2.GarageDoorMessage."
  "MessageType\022\'\n\005creds\030\003 \001(\0132\030.messages2.H"
  "otpHmacCreds\022\014\n\004nmea\030\006 \001(\014\"\276\001\n\013MessageTy"
  "pe\022\010\n\004OPEN\020\000\022\t\n\005RECVD\020\001\022\014\n\010ACCEPTED\020\n\022\024\n"
  "\020ACCEPTED_OPENING\020\013\022\024\n\020ACCEPTED_CLOSING\020"
  "\014\022\n\n\006DENIED\020(\022\021\n\rDENIED_UNAUTH\020)\022\022\n\016DENI"
  "ED_REVOKED\020*\022\024\n\020DENIED_OOB_COUNT\020+\022\027\n\023DE"
  "NIED_OOB_GEOFENCE\020,b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_messages_5fv2_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_messages_5fv2_2eproto_sccs[2] = {
  &scc_info_GarageDoorMessage_messages_5fv2_2eproto.base,
  &scc_info_HotpHmacCreds_messages_5fv2_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_messages_5fv2_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_messages_5fv2_2eproto = {
  false, false, descriptor_table_protodef_messages_5fv2_2eproto, "messages_v2.proto", 427,
  &descriptor_table_messages_5fv2_2eproto_once, descriptor_table_messages_5fv2_2eproto_sccs, descriptor_table_messages_5fv2_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_messages_5fv2_2eproto::offsets,
  file_level_metadata_messages_5fv2_2eproto, 2, file_level_enum_descriptors_messages_5fv2_2eproto, file_level_service_descriptors_messages_5fv2_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_messages_5fv2_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_messages_5fv2_2eproto)), true);
namespace messages2 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GarageDoorMessage_MessageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_messages_5fv2_2eproto);
  return file_level_enum_descriptors_messages_5fv2_2eproto[0];
}
bool GarageDoorMessage_MessageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 10:
    case 11:
    case 12:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr GarageDoorMessage_MessageType GarageDoorMessage::OPEN;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::RECVD;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::ACCEPTED;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::ACCEPTED_OPENING;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::ACCEPTED_CLOSING;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::DENIED;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::DENIED_UNAUTH;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::DENIED_REVOKED;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::DENIED_OOB_COUNT;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::DENIED_OOB_GEOFENCE;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::MessageType_MIN;
constexpr GarageDoorMessage_MessageType GarageDoorMessage::MessageType_MAX;
constexpr int GarageDoorMessage::MessageType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class HotpHmacCreds::_Internal {
 public:
};

HotpHmacCreds::HotpHmacCreds(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:messages2.HotpHmacCreds)
}
HotpHmacCreds::HotpHmacCreds(const HotpHmacCreds& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  nonce_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_nonce().empty()) {
    nonce_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_nonce(), 
      GetArena());
  }
  signature_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_signature().empty()) {
    signature_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_signature(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:messages2.HotpHmacCreds)
}

void HotpHmacCreds::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_HotpHmacCreds_messages_5fv2_2eproto.base);
  nonce_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  signature_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

HotpHmacCreds::~HotpHmacCreds() {
  // @@protoc_insertion_point(destructor:messages2.HotpHmacCreds)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void HotpHmacCreds::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  nonce_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  signature_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void HotpHmacCreds::ArenaDtor(void* object) {
  HotpHmacCreds* _this = reinterpret_cast< HotpHmacCreds* >(object);
  (void)_this;
}
void HotpHmacCreds::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void HotpHmacCreds::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const HotpHmacCreds& HotpHmacCreds::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_HotpHmacCreds_messages_5fv2_2eproto.base);
  return *internal_default_instance();
}


void HotpHmacCreds::Clear() {
// @@protoc_insertion_point(message_clear_start:messages2.HotpHmacCreds)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nonce_.ClearToEmpty();
  signature_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HotpHmacCreds::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes nonce = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_nonce();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes signature = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_signature();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* HotpHmacCreds::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messages2.HotpHmacCreds)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes nonce = 1;
  if (this->nonce().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_nonce(), target);
  }

  // bytes signature = 2;
  if (this->signature().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_signature(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messages2.HotpHmacCreds)
  return target;
}

size_t HotpHmacCreds::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messages2.HotpHmacCreds)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes nonce = 1;
  if (this->nonce().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_nonce());
  }

  // bytes signature = 2;
  if (this->signature().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_signature());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void HotpHmacCreds::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:messages2.HotpHmacCreds)
  GOOGLE_DCHECK_NE(&from, this);
  const HotpHmacCreds* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<HotpHmacCreds>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:messages2.HotpHmacCreds)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:messages2.HotpHmacCreds)
    MergeFrom(*source);
  }
}

void HotpHmacCreds::MergeFrom(const HotpHmacCreds& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:messages2.HotpHmacCreds)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.nonce().size() > 0) {
    _internal_set_nonce(from._internal_nonce());
  }
  if (from.signature().size() > 0) {
    _internal_set_signature(from._internal_signature());
  }
}

void HotpHmacCreds::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:messages2.HotpHmacCreds)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HotpHmacCreds::CopyFrom(const HotpHmacCreds& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messages2.HotpHmacCreds)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HotpHmacCreds::IsInitialized() const {
  return true;
}

void HotpHmacCreds::InternalSwap(HotpHmacCreds* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  nonce_.Swap(&other->nonce_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  signature_.Swap(&other->signature_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata HotpHmacCreds::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GarageDoorMessage::_Internal {
 public:
  static const ::messages2::HotpHmacCreds& creds(const GarageDoorMessage* msg);
};

const ::messages2::HotpHmacCreds&
GarageDoorMessage::_Internal::creds(const GarageDoorMessage* msg) {
  return *msg->creds_;
}
GarageDoorMessage::GarageDoorMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:messages2.GarageDoorMessage)
}
GarageDoorMessage::GarageDoorMessage(const GarageDoorMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_id().empty()) {
    id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_id(), 
      GetArena());
  }
  nmea_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_nmea().empty()) {
    nmea_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_nmea(), 
      GetArena());
  }
  if (from._internal_has_creds()) {
    creds_ = new ::messages2::HotpHmacCreds(*from.creds_);
  } else {
    creds_ = nullptr;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:messages2.GarageDoorMessage)
}

void GarageDoorMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GarageDoorMessage_messages_5fv2_2eproto.base);
  id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  nmea_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&creds_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&creds_)) + sizeof(type_));
}

GarageDoorMessage::~GarageDoorMessage() {
  // @@protoc_insertion_point(destructor:messages2.GarageDoorMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GarageDoorMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  nmea_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete creds_;
}

void GarageDoorMessage::ArenaDtor(void* object) {
  GarageDoorMessage* _this = reinterpret_cast< GarageDoorMessage* >(object);
  (void)_this;
}
void GarageDoorMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GarageDoorMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GarageDoorMessage& GarageDoorMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GarageDoorMessage_messages_5fv2_2eproto.base);
  return *internal_default_instance();
}


void GarageDoorMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:messages2.GarageDoorMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_.ClearToEmpty();
  nmea_.ClearToEmpty();
  if (GetArena() == nullptr && creds_ != nullptr) {
    delete creds_;
  }
  creds_ = nullptr;
  type_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GarageDoorMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "messages2.GarageDoorMessage.id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .messages2.GarageDoorMessage.MessageType type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::messages2::GarageDoorMessage_MessageType>(val));
        } else goto handle_unusual;
        continue;
      // .messages2.HotpHmacCreds creds = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_creds(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes nmea = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_nmea();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GarageDoorMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messages2.GarageDoorMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (this->id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messages2.GarageDoorMessage.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // .messages2.GarageDoorMessage.MessageType type = 2;
  if (this->type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_type(), target);
  }

  // .messages2.HotpHmacCreds creds = 3;
  if (this->has_creds()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::creds(this), target, stream);
  }

  // bytes nmea = 6;
  if (this->nmea().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_nmea(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messages2.GarageDoorMessage)
  return target;
}

size_t GarageDoorMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messages2.GarageDoorMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // bytes nmea = 6;
  if (this->nmea().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_nmea());
  }

  // .messages2.HotpHmacCreds creds = 3;
  if (this->has_creds()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *creds_);
  }

  // .messages2.GarageDoorMessage.MessageType type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GarageDoorMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:messages2.GarageDoorMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const GarageDoorMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GarageDoorMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:messages2.GarageDoorMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:messages2.GarageDoorMessage)
    MergeFrom(*source);
  }
}

void GarageDoorMessage::MergeFrom(const GarageDoorMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:messages2.GarageDoorMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id().size() > 0) {
    _internal_set_id(from._internal_id());
  }
  if (from.nmea().size() > 0) {
    _internal_set_nmea(from._internal_nmea());
  }
  if (from.has_creds()) {
    _internal_mutable_creds()->::messages2::HotpHmacCreds::MergeFrom(from._internal_creds());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
}

void GarageDoorMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:messages2.GarageDoorMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GarageDoorMessage::CopyFrom(const GarageDoorMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messages2.GarageDoorMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GarageDoorMessage::IsInitialized() const {
  return true;
}

void GarageDoorMessage::InternalSwap(GarageDoorMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  id_.Swap(&other->id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  nmea_.Swap(&other->nmea_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GarageDoorMessage, type_)
      + sizeof(GarageDoorMessage::type_)
      - PROTOBUF_FIELD_OFFSET(GarageDoorMessage, creds_)>(
          reinterpret_cast<char*>(&creds_),
          reinterpret_cast<char*>(&other->creds_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GarageDoorMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace messages2
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::messages2::HotpHmacCreds* Arena::CreateMaybeMessage< ::messages2::HotpHmacCreds >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messages2::HotpHmacCreds >(arena);
}
template<> PROTOBUF_NOINLINE ::messages2::GarageDoorMessage* Arena::CreateMaybeMessage< ::messages2::GarageDoorMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messages2::GarageDoorMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
